from django.urls import include, path

from .models import (
    DeviceTypeMapping,
    InterfaceTypeMapping,
    InventoryIgnoreRule,
    ModuleBayMapping,
    ModuleTypeMapping,
    NormalizationRule,
    PlatformMapping,
)
from .views import (
    AddDeviceToLibreNMSView,
    AddDeviceTypeMappingView,
    AssignVCSerialView,
    BulkImportConfirmView,
    BulkImportDevicesView,
    CreateAndAssignPlatformView,
    DeleteNetBoxInterfacesView,
    DeviceCableTableView,
    DeviceClusterUpdateView,
    DeviceConflictActionView,
    DeviceInterfaceTableView,
    DeviceIPAddressTableView,
    DeviceLibreNMSSyncView,
    DeviceModuleTableView,
    DeviceRackUpdateView,
    DeviceRoleUpdateView,
    DeviceStatusListView,
    DeviceTypeMappingBulkDeleteView,
    DeviceTypeMappingBulkImportView,
    DeviceTypeMappingChangeLogView,
    DeviceTypeMappingCreateView,
    DeviceTypeMappingDeleteView,
    DeviceTypeMappingEditView,
    DeviceTypeMappingListView,
    DeviceTypeMappingView,
    DeviceValidationDetailsView,
    DeviceVCDetailsView,
    DeviceVLANTableView,
    InstallBranchView,
    InstallModuleView,
    InstallSelectedView,
    ModuleMismatchPreviewView,
    MoveModuleView,
    ReplaceModuleView,
    UpdateModuleSerialView,
    InterfaceTypeMappingBulkDeleteView,
    InterfaceTypeMappingBulkImportView,
    InterfaceTypeMappingChangeLogView,
    InterfaceTypeMappingCreateView,
    InterfaceTypeMappingDeleteView,
    InterfaceTypeMappingEditView,
    InterfaceTypeMappingListView,
    InterfaceTypeMappingView,
    LibreNMSImportView,
    LibreNMSSettingsView,
    ModuleBayMappingBulkDeleteView,
    ModuleBayMappingBulkImportView,
    ModuleBayMappingChangeLogView,
    ModuleBayMappingCreateView,
    ModuleBayMappingDeleteView,
    ModuleBayMappingEditView,
    ModuleBayMappingListView,
    ModuleBayMappingView,
    ModuleTypeMappingBulkDeleteView,
    ModuleTypeMappingBulkImportView,
    ModuleTypeMappingChangeLogView,
    ModuleTypeMappingCreateView,
    ModuleTypeMappingDeleteView,
    ModuleTypeMappingEditView,
    ModuleTypeMappingListView,
    ModuleTypeMappingView,
    NormalizationRuleBulkDeleteView,
    NormalizationRuleBulkImportView,
    NormalizationRuleChangeLogView,
    NormalizationRuleCreateView,
    NormalizationRuleDeleteView,
    NormalizationRuleEditView,
    NormalizationRuleListView,
    NormalizationRuleView,
    InventoryIgnoreRuleBulkDeleteView,
    InventoryIgnoreRuleBulkImportView,
    InventoryIgnoreRuleChangeLogView,
    InventoryIgnoreRuleCreateView,
    InventoryIgnoreRuleDeleteView,
    InventoryIgnoreRuleEditView,
    InventoryIgnoreRuleListView,
    InventoryIgnoreRuleView,
    DeviceTypeMappingBulkExportYAMLView,
    InterfaceTypeMappingBulkExportYAMLView,
    ModuleBayMappingBulkExportYAMLView,
    ModuleTypeMappingBulkExportYAMLView,
    NormalizationRuleBulkExportYAMLView,
    InventoryIgnoreRuleBulkExportYAMLView,
    PlatformMappingBulkDeleteView,
    PlatformMappingBulkExportYAMLView,
    PlatformMappingBulkImportView,
    PlatformMappingChangeLogView,
    PlatformMappingCreateView,
    PlatformMappingDeleteView,
    PlatformMappingEditView,
    PlatformMappingListView,
    PlatformMappingView,
    RemoveServerMappingView,
    SaveUserPrefView,
    SingleCableVerifyView,
    SingleInterfaceVerifyView,
    SingleIPAddressVerifyView,
    SaveVlanGroupOverridesView,
    SingleVlanGroupVerifyView,
    VerifyVlanSyncGroupView,
    SyncCablesView,
    SyncInterfacesView,
    SyncIPAddressesView,
    SyncSiteLocationView,
    SyncVLANsView,
    TestLibreNMSConnectionView,
    UpdateDeviceLocationView,
    UpdateDeviceNameView,
    UpdateDevicePlatformView,
    UpdateDeviceSerialView,
    UpdateDeviceTypeView,
    VMInterfaceTableView,
    VMIPAddressTableView,
    VMLibreNMSSyncView,
    VMStatusListView,
    ConvertLegacyLibreNMSIdView,
)

urlpatterns = [
    # Device sync URLs
    path(
        "device/<int:pk>/librenms-sync/",
        DeviceLibreNMSSyncView.as_view(),
        name="device_librenms_sync",
    ),
    path(
        "devices/<int:pk>/interface-sync/",
        DeviceInterfaceTableView.as_view(),
        name="device_interface_sync",
    ),
    path(
        "devices/<int:pk>/cable-sync/",
        DeviceCableTableView.as_view(),
        name="device_cable_sync",
    ),
    path(
        "devices/<int:pk>/module-sync/",
        DeviceModuleTableView.as_view(),
        name="device_module_sync",
    ),
    path(
        "devices/<int:pk>/install-module/",
        InstallModuleView.as_view(),
        name="install_module",
    ),
    path(
        "devices/<int:pk>/install-branch/",
        InstallBranchView.as_view(),
        name="install_branch",
    ),
    path(
        "devices/<int:pk>/install-selected/",
        InstallSelectedView.as_view(),
        name="install_selected",
    ),
    path(
        "devices/<int:pk>/update-module-serial/",
        UpdateModuleSerialView.as_view(),
        name="update_module_serial",
    ),
    path(
        "devices/<int:pk>/module-mismatch-preview/",
        ModuleMismatchPreviewView.as_view(),
        name="module_mismatch_preview",
    ),
    path(
        "devices/<int:pk>/replace-module/",
        ReplaceModuleView.as_view(),
        name="replace_module",
    ),
    path(
        "devices/<int:pk>/move-module/",
        MoveModuleView.as_view(),
        name="move_module",
    ),
    path(
        "devices/<int:pk>/ipaddress-sync/",
        DeviceIPAddressTableView.as_view(),
        name="device_ipaddress_sync",
    ),
    # Path for single interface verify javascript call
    path(
        "verify-interface/",
        SingleInterfaceVerifyView.as_view(),
        name="verify_interface",
    ),
    path(
        "verify-cable/",
        SingleCableVerifyView.as_view(),
        name="verify_cable",
    ),
    # Path for single IP address verify javascript call
    path(
        "verify-ipaddress/",
        SingleIPAddressVerifyView.as_view(),
        name="verify_ipaddress",
    ),
    # Path for VLAN group verify javascript call (interface VLAN coloring)
    path(
        "verify-vlan-group/",
        SingleVlanGroupVerifyView.as_view(),
        name="verify_vlan_group",
    ),
    # Verify VLAN existence in a group (VLAN sync tab coloring)
    path(
        "verify-vlan-sync-group/",
        VerifyVlanSyncGroupView.as_view(),
        name="verify_vlan_sync_group",
    ),
    # Save VLAN group overrides to cache ("apply to all" persistence)
    path(
        "save-vlan-group-overrides/",
        SaveVlanGroupOverridesView.as_view(),
        name="save_vlan_group_overrides",
    ),
    # Virtual machine sync URLs
    path(
        "virtual-machines/<int:pk>/interface-sync/",
        VMInterfaceTableView.as_view(),
        name="vm_interface_sync",
    ),
    path(
        "virtual-machines/<int:pk>/ipaddress-sync/",
        VMIPAddressTableView.as_view(),
        name="vm_ipaddress_sync",
    ),
    path(
        "virtual-machines/<int:pk>/librenms-sync/",
        VMLibreNMSSyncView.as_view(),
        name="vm_librenms_sync",
    ),
    # Sync interfaces URL
    path(
        "<str:object_type>/<int:object_id>/sync-interfaces/",
        SyncInterfacesView.as_view(),
        name="sync_selected_interfaces",
    ),
    # Delete NetBox-only interfaces URL
    path(
        "<str:object_type>/<int:object_id>/delete-netbox-interfaces/",
        DeleteNetBoxInterfacesView.as_view(),
        name="delete_netbox_interfaces",
    ),
    # Sync cables URL
    path(
        "device/<int:pk>/sync-cables/",
        SyncCablesView.as_view(),
        name="sync_device_cables",
    ),
    # Sync IP addresses URL
    path(
        "<str:object_type>/<int:pk>/sync-ip-addresses/",
        SyncIPAddressesView.as_view(),
        name="sync_device_ip_addresses",
    ),
    # VLAN sync URLs
    path(
        "devices/<int:pk>/vlan-sync/",
        DeviceVLANTableView.as_view(),
        name="device_vlan_sync",
    ),
    path(
        "<str:object_type>/<int:object_id>/sync-vlans/",
        SyncVLANsView.as_view(),
        name="sync_selected_vlans",
    ),
    # Add Device to LibreNMS URLs
    path(
        "add-device/<int:object_id>/",
        AddDeviceToLibreNMSView.as_view(),
        name="add_device_to_librenms",
    ),
    # Site > location sync URLs
    path(
        "site-location-comparison/",
        SyncSiteLocationView.as_view(),
        name="site_location_sync",
    ),
    path(
        "create-librenms-location/<int:pk>/",
        SyncSiteLocationView.as_view(),
        name="create_librenms_location",
    ),
    path(
        "update-librenms-location/<int:pk>/",
        SyncSiteLocationView.as_view(),
        name="update_librenms_location",
    ),
    # Update device location URLs
    path(
        "devices/<int:pk>/update-location/",
        UpdateDeviceLocationView.as_view(),
        name="update_device_location",
    ),
    # Update device field URLs (name, serial, device type, platform)
    path(
        "devices/<int:pk>/update-name/",
        UpdateDeviceNameView.as_view(),
        name="update_device_name",
    ),
    path(
        "devices/<int:pk>/update-serial/",
        UpdateDeviceSerialView.as_view(),
        name="update_device_serial",
    ),
    path(
        "devices/<int:pk>/update-device-type/",
        UpdateDeviceTypeView.as_view(),
        name="update_device_type",
    ),
    path(
        "devices/<int:pk>/update-platform/",
        UpdateDevicePlatformView.as_view(),
        name="update_device_platform",
    ),
    path(
        "devices/<int:pk>/create-and-assign-platform/",
        CreateAndAssignPlatformView.as_view(),
        name="create_and_assign_platform",
    ),
    path(
        "devices/<int:pk>/assign-vc-serial/",
        AssignVCSerialView.as_view(),
        name="assign_vc_serial",
    ),
    path(
        "devices/<int:pk>/remove-server-mapping/",
        RemoveServerMappingView.as_view(),
        name="remove_server_mapping",
    ),
    path(
        "devices/<int:pk>/convert-legacy-id/",
        ConvertLegacyLibreNMSIdView.as_view(),
        name="convert_legacy_librenms_id",
    ),
    path(
        "device-status/",
        DeviceStatusListView.as_view(),
        name="device_status_list",
    ),
    path(
        "librenms-import/",
        LibreNMSImportView.as_view(),
        name="librenms_import",
    ),
    path(
        "device-import/bulk/",
        BulkImportDevicesView.as_view(),
        name="bulk_import_devices",
    ),
    path(
        "device-import/bulk/confirm/",
        BulkImportConfirmView.as_view(),
        name="bulk_import_confirm",
    ),
    path(
        "device-import/validation/<str:device_id>/",
        DeviceValidationDetailsView.as_view(),
        name="device_validation_details",
    ),
    path(
        "device-import/vc-details/<str:device_id>/",
        DeviceVCDetailsView.as_view(),
        name="device_vc_details",
    ),
    path(
        "device-import/role-update/<str:device_id>/",
        DeviceRoleUpdateView.as_view(),
        name="device_role_update",
    ),
    path(
        "device-import/cluster-update/<str:device_id>/",
        DeviceClusterUpdateView.as_view(),
        name="device_cluster_update",
    ),
    path(
        "device-import/rack-update/<str:device_id>/",
        DeviceRackUpdateView.as_view(),
        name="device_rack_update",
    ),
    path(
        "device-import/conflict-action/<str:device_id>/",
        DeviceConflictActionView.as_view(),
        name="device_conflict_action",
    ),
    path(
        "device-import/add-device-type-mapping/<str:device_id>/",
        AddDeviceTypeMappingView.as_view(),
        name="add_device_type_mapping",
    ),
    path(
        "save-user-pref/",
        SaveUserPrefView.as_view(),
        name="save_user_pref",
    ),
    path(
        "vm-status/",
        VMStatusListView.as_view(),
        name="vm_status_list",
    ),
    # Settings URL
    path(
        "settings/",
        LibreNMSSettingsView.as_view(),
        name="settings",
    ),
    # Test LibreNMS connection endpoint
    path(
        "settings/test-connection/",
        TestLibreNMSConnectionView.as_view(),
        name="test_connection",
    ),
    # Interface type mapping URLs
    path(
        "interface-type-mappings/",
        InterfaceTypeMappingListView.as_view(),
        name="interfacetypemapping_list",
    ),
    path(
        "interface-type-mappings/<int:pk>/",
        InterfaceTypeMappingView.as_view(),
        name="interfacetypemapping_detail",
    ),
    path(
        "interface-type-mappings/add/",
        InterfaceTypeMappingCreateView.as_view(),
        name="interfacetypemapping_add",
    ),
    path(
        "interface-type-mappings/import/",
        InterfaceTypeMappingBulkImportView.as_view(),
        name="interfacetypemapping_bulk_import",
    ),
    path(
        "interface-type-mappings/<int:pk>/delete/",
        InterfaceTypeMappingDeleteView.as_view(),
        name="interfacetypemapping_delete",
    ),
    path(
        "interface-type-mappings/<int:pk>/edit/",
        InterfaceTypeMappingEditView.as_view(),
        name="interfacetypemapping_edit",
    ),
    path(
        "interface-type-mappings/<int:pk>/changelog/",
        InterfaceTypeMappingChangeLogView.as_view(),
        name="interfacetypemapping_changelog",
        kwargs={"model": InterfaceTypeMapping},
    ),
    path(
        "interface-type-mappings/delete/",
        InterfaceTypeMappingBulkDeleteView.as_view(),
        name="interfacetypemapping_bulk_delete",
    ),
    # Device type mapping URLs
    path(
        "device-type-mappings/",
        DeviceTypeMappingListView.as_view(),
        name="devicetypemapping_list",
    ),
    path(
        "device-type-mappings/<int:pk>/",
        DeviceTypeMappingView.as_view(),
        name="devicetypemapping_detail",
    ),
    path(
        "device-type-mappings/add/",
        DeviceTypeMappingCreateView.as_view(),
        name="devicetypemapping_add",
    ),
    path(
        "device-type-mappings/import/",
        DeviceTypeMappingBulkImportView.as_view(),
        name="devicetypemapping_bulk_import",
    ),
    path(
        "device-type-mappings/<int:pk>/delete/",
        DeviceTypeMappingDeleteView.as_view(),
        name="devicetypemapping_delete",
    ),
    path(
        "device-type-mappings/<int:pk>/edit/",
        DeviceTypeMappingEditView.as_view(),
        name="devicetypemapping_edit",
    ),
    path(
        "device-type-mappings/<int:pk>/changelog/",
        DeviceTypeMappingChangeLogView.as_view(),
        name="devicetypemapping_changelog",
        kwargs={"model": DeviceTypeMapping},
    ),
    path(
        "device-type-mappings/delete/",
        DeviceTypeMappingBulkDeleteView.as_view(),
        name="devicetypemapping_bulk_delete",
    ),
    # Module type mapping URLs
    path(
        "module-type-mappings/",
        ModuleTypeMappingListView.as_view(),
        name="moduletypemapping_list",
    ),
    path(
        "module-type-mappings/<int:pk>/",
        ModuleTypeMappingView.as_view(),
        name="moduletypemapping_detail",
    ),
    path(
        "module-type-mappings/add/",
        ModuleTypeMappingCreateView.as_view(),
        name="moduletypemapping_add",
    ),
    path(
        "module-type-mappings/import/",
        ModuleTypeMappingBulkImportView.as_view(),
        name="moduletypemapping_bulk_import",
    ),
    path(
        "module-type-mappings/<int:pk>/delete/",
        ModuleTypeMappingDeleteView.as_view(),
        name="moduletypemapping_delete",
    ),
    path(
        "module-type-mappings/<int:pk>/edit/",
        ModuleTypeMappingEditView.as_view(),
        name="moduletypemapping_edit",
    ),
    path(
        "module-type-mappings/<int:pk>/changelog/",
        ModuleTypeMappingChangeLogView.as_view(),
        name="moduletypemapping_changelog",
        kwargs={"model": ModuleTypeMapping},
    ),
    path(
        "module-type-mappings/delete/",
        ModuleTypeMappingBulkDeleteView.as_view(),
        name="moduletypemapping_bulk_delete",
    ),
    # Module Bay Mapping URLs
    path(
        "module-bay-mappings/",
        ModuleBayMappingListView.as_view(),
        name="modulebaymapping_list",
    ),
    path(
        "module-bay-mappings/<int:pk>/",
        ModuleBayMappingView.as_view(),
        name="modulebaymapping_detail",
    ),
    path(
        "module-bay-mappings/add/",
        ModuleBayMappingCreateView.as_view(),
        name="modulebaymapping_add",
    ),
    path(
        "module-bay-mappings/import/",
        ModuleBayMappingBulkImportView.as_view(),
        name="modulebaymapping_bulk_import",
    ),
    path(
        "module-bay-mappings/<int:pk>/delete/",
        ModuleBayMappingDeleteView.as_view(),
        name="modulebaymapping_delete",
    ),
    path(
        "module-bay-mappings/<int:pk>/edit/",
        ModuleBayMappingEditView.as_view(),
        name="modulebaymapping_edit",
    ),
    path(
        "module-bay-mappings/<int:pk>/changelog/",
        ModuleBayMappingChangeLogView.as_view(),
        name="modulebaymapping_changelog",
        kwargs={"model": ModuleBayMapping},
    ),
    path(
        "module-bay-mappings/delete/",
        ModuleBayMappingBulkDeleteView.as_view(),
        name="modulebaymapping_bulk_delete",
    ),
    # Normalization Rule URLs
    path(
        "normalization-rules/",
        NormalizationRuleListView.as_view(),
        name="normalizationrule_list",
    ),
    path(
        "normalization-rules/<int:pk>/",
        NormalizationRuleView.as_view(),
        name="normalizationrule_detail",
    ),
    path(
        "normalization-rules/add/",
        NormalizationRuleCreateView.as_view(),
        name="normalizationrule_add",
    ),
    path(
        "normalization-rules/import/",
        NormalizationRuleBulkImportView.as_view(),
        name="normalizationrule_bulk_import",
    ),
    path(
        "normalization-rules/<int:pk>/delete/",
        NormalizationRuleDeleteView.as_view(),
        name="normalizationrule_delete",
    ),
    path(
        "normalization-rules/<int:pk>/edit/",
        NormalizationRuleEditView.as_view(),
        name="normalizationrule_edit",
    ),
    path(
        "normalization-rules/<int:pk>/changelog/",
        NormalizationRuleChangeLogView.as_view(),
        name="normalizationrule_changelog",
        kwargs={"model": NormalizationRule},
    ),
    path(
        "normalization-rules/delete/",
        NormalizationRuleBulkDeleteView.as_view(),
        name="normalizationrule_bulk_delete",
    ),
    # Inventory Ignore Rule URLs
    path(
        "inventory-ignore-rules/",
        InventoryIgnoreRuleListView.as_view(),
        name="inventoryignorerule_list",
    ),
    path(
        "inventory-ignore-rules/<int:pk>/",
        InventoryIgnoreRuleView.as_view(),
        name="inventoryignorerule_detail",
    ),
    path(
        "inventory-ignore-rules/add/",
        InventoryIgnoreRuleCreateView.as_view(),
        name="inventoryignorerule_add",
    ),
    path(
        "inventory-ignore-rules/import/",
        InventoryIgnoreRuleBulkImportView.as_view(),
        name="inventoryignorerule_bulk_import",
    ),
    path(
        "inventory-ignore-rules/<int:pk>/delete/",
        InventoryIgnoreRuleDeleteView.as_view(),
        name="inventoryignorerule_delete",
    ),
    path(
        "inventory-ignore-rules/<int:pk>/edit/",
        InventoryIgnoreRuleEditView.as_view(),
        name="inventoryignorerule_edit",
    ),
    path(
        "inventory-ignore-rules/<int:pk>/changelog/",
        InventoryIgnoreRuleChangeLogView.as_view(),
        name="inventoryignorerule_changelog",
        kwargs={"model": InventoryIgnoreRule},
    ),
    path(
        "inventory-ignore-rules/delete/",
        InventoryIgnoreRuleBulkDeleteView.as_view(),
        name="inventoryignorerule_bulk_delete",
    ),
    # Bulk YAML export URLs for all mapping models
    path(
        "interface-type-mappings/export-yaml/",
        InterfaceTypeMappingBulkExportYAMLView.as_view(),
        name="interfacetypemapping_bulk_export_yaml",
    ),
    path(
        "device-type-mappings/export-yaml/",
        DeviceTypeMappingBulkExportYAMLView.as_view(),
        name="devicetypemapping_bulk_export_yaml",
    ),
    path(
        "module-type-mappings/export-yaml/",
        ModuleTypeMappingBulkExportYAMLView.as_view(),
        name="moduletypemapping_bulk_export_yaml",
    ),
    path(
        "module-bay-mappings/export-yaml/",
        ModuleBayMappingBulkExportYAMLView.as_view(),
        name="modulebaymapping_bulk_export_yaml",
    ),
    path(
        "normalization-rules/export-yaml/",
        NormalizationRuleBulkExportYAMLView.as_view(),
        name="normalizationrule_bulk_export_yaml",
    ),
    path(
        "inventory-ignore-rules/export-yaml/",
        InventoryIgnoreRuleBulkExportYAMLView.as_view(),
        name="inventoryignorerule_bulk_export_yaml",
    ),
    # Platform Mapping URLs
    path(
        "platform-mappings/",
        PlatformMappingListView.as_view(),
        name="platformmapping_list",
    ),
    path(
        "platform-mappings/<int:pk>/",
        PlatformMappingView.as_view(),
        name="platformmapping_detail",
    ),
    path(
        "platform-mappings/add/",
        PlatformMappingCreateView.as_view(),
        name="platformmapping_add",
    ),
    path(
        "platform-mappings/import/",
        PlatformMappingBulkImportView.as_view(),
        name="platformmapping_bulk_import",
    ),
    path(
        "platform-mappings/<int:pk>/delete/",
        PlatformMappingDeleteView.as_view(),
        name="platformmapping_delete",
    ),
    path(
        "platform-mappings/<int:pk>/edit/",
        PlatformMappingEditView.as_view(),
        name="platformmapping_edit",
    ),
    path(
        "platform-mappings/<int:pk>/changelog/",
        PlatformMappingChangeLogView.as_view(),
        name="platformmapping_changelog",
        kwargs={"model": PlatformMapping},
    ),
    path(
        "platform-mappings/delete/",
        PlatformMappingBulkDeleteView.as_view(),
        name="platformmapping_bulk_delete",
    ),
    path(
        "platform-mappings/export-yaml/",
        PlatformMappingBulkExportYAMLView.as_view(),
        name="platformmapping_bulk_export_yaml",
    ),
    path("api/", include("netbox_librenms_plugin.api.urls")),
]
