"""
Module for initializing views for the NetBox LibreNMS plugin.

All imports below are intentional re-exports consumed by urls.py and
other modules.  The package-level F401 per-file-ignore keeps them from
reading as unused here.
"""

from .base.cables_view import BaseCableTableView, CableRemotePickerView, SingleCableVerifyView
from .base.interfaces_view import BaseInterfaceTableView
from .data_shapes import CaptureDataShapeView
from .base.ip_addresses_view import BaseIPAddressTableView, SingleIPAddressVerifyView
from .base.librenms_sync_view import BaseLibreNMSSyncView
from .base.vlan_table_view import BaseVLANTableView
from .imports import (
    BulkImportConfirmView,
    BulkImportDevicesView,
    CreatePlatformFromImportView,
    DeviceClusterUpdateView,
    DeviceConflictActionView,
    DeviceImportPlanUpdateView,
    DeviceRackUpdateView,
    DeviceRoleUpdateView,
    DeviceValidationDetailsView,
    DeviceVCDetailsView,
    LibreNMSImportView,
    SaveUserPrefView,
)
from .imports.actions import (
    AddAsOOBView,
    AddDeviceTypeMappingView,
    AddPlatformMappingView,
    MergeNetBoxDevicesView,
    PromoteToHostView,
)
from .mapping_views import (
    CarrierAutoInstallRuleBulkDeleteView,
    CarrierAutoInstallRuleBulkExportYAMLView,
    CarrierAutoInstallRuleBulkImportView,
    CarrierAutoInstallRuleChangeLogView,
    CarrierAutoInstallRuleCreateView,
    CarrierAutoInstallRuleDeleteView,
    CarrierAutoInstallRuleEditView,
    CarrierAutoInstallRuleListView,
    CarrierAutoInstallRuleView,
    DeviceTypeMappingBulkDeleteView,
    DeviceTypeMappingBulkExportYAMLView,
    DeviceTypeMappingBulkImportView,
    DeviceTypeMappingChangeLogView,
    DeviceTypeMappingCreateView,
    DeviceTypeMappingDeleteView,
    DeviceTypeMappingEditView,
    DeviceTypeMappingListView,
    DeviceTypeMappingView,
    InterfaceTypeMappingBulkDeleteView,
    InterfaceTypeMappingBulkExportYAMLView,
    InterfaceTypeMappingBulkImportView,
    InterfaceTypeMappingChangeLogView,
    InterfaceTypeMappingCreateView,
    InterfaceTypeMappingDeleteView,
    InterfaceTypeMappingEditView,
    InterfaceTypeMappingListView,
    InterfaceTypeMappingView,
    InventoryIgnoreRuleBulkDeleteView,
    InventoryIgnoreRuleBulkExportYAMLView,
    InventoryIgnoreRuleBulkImportView,
    InventoryIgnoreRuleChangeLogView,
    InventoryIgnoreRuleCreateView,
    InventoryIgnoreRuleDeleteView,
    InventoryIgnoreRuleEditView,
    InventoryIgnoreRuleListView,
    InventoryIgnoreRuleView,
    LocationMappingBulkDeleteView,
    LocationMappingBulkExportYAMLView,
    LocationMappingBulkImportView,
    LocationMappingChangeLogView,
    LocationMappingCreateView,
    LocationMappingDeleteView,
    LocationMappingEditView,
    LocationMappingListView,
    LocationMappingView,
    ModuleBayMappingBulkDeleteView,
    ModuleBayMappingBulkExportYAMLView,
    ModuleBayMappingBulkImportView,
    ModuleBayMappingChangeLogView,
    ModuleBayMappingCreateView,
    ModuleBayMappingDeleteView,
    ModuleBayMappingEditView,
    ModuleBayMappingListView,
    ModuleBayMappingView,
    ModuleTypeMappingBulkDeleteView,
    ModuleTypeMappingBulkExportYAMLView,
    ModuleTypeMappingBulkImportView,
    ModuleTypeMappingChangeLogView,
    ModuleTypeMappingCreateView,
    ModuleTypeMappingDeleteView,
    ModuleTypeMappingEditView,
    ModuleTypeMappingListView,
    ModuleTypeMappingView,
    NormalizationRuleBulkDeleteView,
    NormalizationRuleBulkExportYAMLView,
    NormalizationRuleBulkImportView,
    NormalizationRuleChangeLogView,
    NormalizationRuleCreateView,
    NormalizationRuleDeleteView,
    NormalizationRuleEditView,
    NormalizationRuleListView,
    NormalizationRuleView,
    PlatformMappingBulkDeleteView,
    PlatformMappingBulkExportYAMLView,
    PlatformMappingBulkImportView,
    PlatformMappingChangeLogView,
    PlatformMappingCreateView,
    PlatformMappingDeleteView,
    PlatformMappingEditView,
    PlatformMappingListView,
    PlatformMappingView,
    PortStackLagPatternBulkDeleteView,
    PortStackLagPatternBulkExportYAMLView,
    PortStackLagPatternBulkImportView,
    PortStackLagPatternChangeLogView,
    PortStackLagPatternCreateView,
    PortStackLagPatternDeleteView,
    PortStackLagPatternEditView,
    PortStackLagPatternListView,
    PortStackLagPatternView,
    SerialSensorTypePatternBulkDeleteView,
    SerialSensorTypePatternBulkExportYAMLView,
    SerialSensorTypePatternBulkImportView,
    SerialSensorTypePatternChangeLogView,
    SerialSensorTypePatternCreateView,
    SerialSensorTypePatternDeleteView,
    SerialSensorTypePatternEditView,
    SerialSensorTypePatternListView,
    SerialSensorTypePatternView,
)
from .object_sync import (
    DeviceCableTableView,
    DeviceInterfaceTableView,
    DeviceIPAddressTableView,
    DeviceLibreNMSSyncView,
    DeviceModuleTableView,
    DeviceVLANTableView,
    SaveVlanGroupOverridesView,
    SingleInterfaceVerifyView,
    SingleModuleVerifyView,
    SingleVlanGroupVerifyView,
    SyncCacheFragmentView,
    SyncCacheStatusView,
    VerifyVlanSyncGroupView,
    VMInterfaceTableView,
    VMIPAddressTableView,
    VMLibreNMSSyncView,
)
from .settings_views import LibreNMSSettingsView, TestLibreNMSConnectionView
from .status_check import DeviceStatusListView, VMStatusListView
from .sync.cables import SyncCablesView
from .sync.device_fields import (
    AssignVCSerialView,
    ConvertLegacyLibreNMSIdView,
    CreateAndAssignPlatformView,
    RemoveServerMappingView,
    SetPreferredServerView,
    UpdateDeviceNameView,
    UpdateDevicePlatformView,
    UpdateDeviceSerialView,
    UpdateDeviceTypeView,
)
from .sync.devices import AddDeviceToLibreNMSView, UpdateDeviceLocationView
from .sync.interfaces import (
    DeleteNetBoxInterfacesView,
    SyncInterfaceBridgeView,
    SyncInterfaceLagView,
    SyncInterfaceParentView,
    SyncInterfacesView,
)
from .sync.ip_addresses import SyncIPAddressesView
from .sync.locations import SyncSiteLocationView
from .sync.migrate import (
    MoveInterfaceToWinnerView,
    MoveIPAddressToWinnerView,
    TransferDeviceIPView,
)
from .sync.modules import (
    AddBayTemplateView,
    InstallBranchView,
    InstallModuleView,
    InstallSelectedView,
    ModuleMismatchPreviewView,
    MoveModuleView,
    ReplaceModuleView,
    UpdateModuleInterfaceView,
    UpdateModuleSerialView,
    VCNormalizationReportView,
)
from .sync.vlans import SyncVLANsView
