# Generated by Django 5.1.4 on 2025-08-07 12:50

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0122_charfield_null_choices"),
        ("netbox_librenms_plugin", "0003_interfacetypemapping_librenms_speed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibreNMSSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "selected_server",
                    models.CharField(default="default", max_length=100),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "LibreNMS Settings",
                "verbose_name_plural": "LibreNMS Settings",
            },
        ),
    ]
