# Generated by Django 5.1.4 on 2025-08-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_librenms_plugin", "0004_librenmssettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="librenmssettings",
            name="created",
        ),
        migrations.RemoveField(
            model_name="librenmssettings",
            name="custom_field_data",
        ),
        migrations.RemoveField(
            model_name="librenmssettings",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="librenmssettings",
            name="tags",
        ),
    ]
