# Generated by Django 5.2.13 on 2026-05-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0134_owner"),
        ("netbox_librenms_plugin", "0010_inventory_models"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="interfacetypemapping",
            name="unique_interface_type_mapping",
        ),
        migrations.AddConstraint(
            model_name="interfacetypemapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("librenms_speed__isnull", False)),
                fields=("librenms_type", "librenms_speed"),
                name="unique_interface_type_mapping",
            ),
        ),
        migrations.AddConstraint(
            model_name="interfacetypemapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("librenms_speed__isnull", True)),
                fields=("librenms_type",),
                name="unique_interface_type_mapping_wildcard",
            ),
        ),
    ]
