# Generated by Django 5.2.13 on 2026-05-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_librenms_plugin", "0011_locationmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="librenmssettings",
            name="location_parse_is_regex",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="librenmssettings",
            name="location_parse_pattern",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
