# Generated by Django 5.2.13 on 2026-05-09 05:55

import django.db.models.deletion
import netbox.models.deletion
import netbox_librenms_plugin.models
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0227_alter_interface_speed_bigint"),
        ("extras", "0134_owner"),
        ("netbox_librenms_plugin", "0011_interfacetypemapping_wildcard_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarrierAutoInstallRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("device_type_pattern", models.CharField(blank=True, max_length=255)),
                ("librenms_child_class", models.CharField(max_length=50)),
                ("librenms_child_name_pattern", models.CharField(max_length=255)),
                ("netbox_bay_name_pattern", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "carrier_module_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="librenms_carrier_install_rules",
                        to="dcim.moduletype",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="librenms_carrier_install_rules",
                        to="dcim.manufacturer",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ["manufacturer__name", "librenms_child_class", "librenms_child_name_pattern"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "manufacturer",
                            "device_type_pattern",
                            "librenms_child_class",
                            "librenms_child_name_pattern",
                            "netbox_bay_name_pattern",
                        ),
                        name="unique_carrier_auto_install_rule",
                    )
                ],
            },
            bases=(
                netbox_librenms_plugin.models.FullCleanOnSaveMixin,
                netbox.models.deletion.DeleteMixin,
                models.Model,
            ),
        ),
    ]
