# Generated by Django 5.2.13 on 2026-05-29 13:40

import django.db.models.deletion
import django.db.models.functions.text
import netbox.models.deletion
import netbox_librenms_plugin.models
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0134_owner"),
        ("netbox_librenms_plugin", "0011_renormalize_device_type_mappings"),
    ]

    operations = [
        migrations.AddField(
            model_name="librenmssettings",
            name="location_parse_is_regex",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="librenmssettings",
            name="location_parse_pattern",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="LocationMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("field_type", models.CharField(max_length=20)),
                ("librenms_value", models.CharField(max_length=255)),
                ("object_id", models.PositiveBigIntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="contenttypes.contenttype"
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ["field_type", "librenms_value"],
            },
            bases=(
                netbox_librenms_plugin.models.FullCleanOnSaveMixin,
                netbox.models.deletion.DeleteMixin,
                models.Model,
            ),
        ),
        migrations.AddConstraint(
            model_name="locationmapping",
            constraint=models.UniqueConstraint(
                models.F("field_type"),
                django.db.models.functions.text.Lower("librenms_value"),
                condition=models.Q(("field_type__in", ["site", "tenant"])),
                name="uniq_locationmapping_unscoped_ci",
            ),
        ),
    ]
