# Generated by Django 5.2.13 on 2026-05-09 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0227_alter_interface_speed_bigint"),
        ("extras", "0134_owner"),
        ("netbox_librenms_plugin", "0012_carrierautoinstallrule"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="modulebaymapping",
            name="unique_module_bay_mapping",
        ),
        migrations.AddField(
            model_name="modulebaymapping",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="librenms_module_bay_mappings",
                to="dcim.manufacturer",
            ),
        ),
        migrations.AddConstraint(
            model_name="modulebaymapping",
            constraint=models.UniqueConstraint(
                fields=("librenms_name", "librenms_class", "manufacturer"), name="unique_module_bay_mapping"
            ),
        ),
    ]
