# Generated by Django 5.2.13 on 2026-06-01 08:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0134_owner"),
        ("netbox_librenms_plugin", "0013_librenmssettings_location_parse_is_regex_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="locationmapping",
            constraint=models.UniqueConstraint(
                models.F("field_type"),
                django.db.models.functions.text.Lower("librenms_value"),
                condition=models.Q(("field_type__in", ["region", "site", "tenant"])),
                name="uniq_locationmapping_unscoped_ci",
            ),
        ),
    ]
