# Generated by Django 5.2.13 on 2026-05-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0227_alter_interface_speed_bigint"),
        ("extras", "0134_owner"),
        ("netbox_librenms_plugin", "0013_modulebaymapping_manufacturer"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="carrierautoinstallrule",
            name="unique_carrier_auto_install_rule",
        ),
        migrations.RemoveConstraint(
            model_name="modulebaymapping",
            name="unique_module_bay_mapping",
        ),
        migrations.AddConstraint(
            model_name="carrierautoinstallrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("manufacturer__isnull", False)),
                fields=(
                    "manufacturer",
                    "device_type_pattern",
                    "librenms_child_class",
                    "librenms_child_name_pattern",
                    "netbox_bay_name_pattern",
                ),
                name="unique_carrier_auto_install_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="carrierautoinstallrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("manufacturer__isnull", True)),
                fields=(
                    "device_type_pattern",
                    "librenms_child_class",
                    "librenms_child_name_pattern",
                    "netbox_bay_name_pattern",
                ),
                name="unique_carrier_auto_install_rule_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="modulebaymapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("manufacturer__isnull", False)),
                fields=("librenms_name", "librenms_class", "manufacturer"),
                name="unique_module_bay_mapping",
            ),
        ),
        migrations.AddConstraint(
            model_name="modulebaymapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("manufacturer__isnull", True)),
                fields=("librenms_name", "librenms_class"),
                name="unique_module_bay_mapping_global",
            ),
        ),
    ]
