# Generated by Django 5.2.13 on 2026-05-11 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0227_alter_interface_speed_bigint"),
        ("extras", "0134_owner"),
        ("netbox_librenms_plugin", "0014_tighten_nullable_manufacturer_unique_constraints"),
    ]

    operations = [
        # Drop the table-level UNIQUE on librenms_model so we can scope the
        # mapping per manufacturer (the same LibreNMS model string may need
        # different NetBox ModuleTypes for different vendors).
        migrations.AlterField(
            model_name="moduletypemapping",
            name="librenms_model",
            field=models.CharField(
                help_text="Model name from LibreNMS inventory (entPhysicalModelName)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="moduletypemapping",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="librenms_module_type_mappings",
                to="dcim.manufacturer",
                help_text=(
                    "Optional: scope this mapping to one manufacturer (matches the device's "
                    "device_type.manufacturer). Leave blank to apply across vendors. When both a "
                    "manufacturer-scoped and a global mapping exist for the same librenms_model, "
                    "the manufacturer-scoped row wins for devices of that vendor."
                ),
            ),
        ),
        # Replace the dropped table-level UNIQUE with a conditional pair:
        # NOT NULL manufacturer → unique on (librenms_model, manufacturer);
        # NULL manufacturer     → unique on (librenms_model) alone.
        # This pattern matches the one used for ModuleBayMapping in 0014 and
        # works on PG <13 where NULL values in unique indexes are distinct.
        migrations.AddConstraint(
            model_name="moduletypemapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("manufacturer__isnull", False)),
                fields=("librenms_model", "manufacturer"),
                name="unique_module_type_mapping",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduletypemapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("manufacturer__isnull", True)),
                fields=("librenms_model",),
                name="unique_module_type_mapping_global",
            ),
        ),
    ]
