# Generated by Django 6.1 on 2026-09-15 12:25

from django.db import migrations, models

BRIDGE_OS = "linux"
BRIDGE_PATTERN = r"^(vmbr|br|bridge)\d+$"
LAG_PATTERN = r"^bond\d+$"
SEEDED_DESCRIPTION = "Linux bond and bridge interface names."


def _normalized(value):
    """Normalize an OS name in the same way as the model constraint."""
    return (value or "").strip().lower()


def populate_bridge_pattern(apps, schema_editor):
    """Add the default Linux bridge rule without replacing operator data."""
    alias = schema_editor.connection.alias
    PortStackLagPattern = apps.get_model("netbox_librenms_plugin", "PortStackLagPattern")
    rows = PortStackLagPattern.objects.using(alias)
    existing = next((row for row in rows.all() if _normalized(row.librenms_os) == BRIDGE_OS), None)
    if existing is None:
        rows.create(
            librenms_os=BRIDGE_OS,
            lag_name_pattern=LAG_PATTERN,
            bridge_name_pattern=BRIDGE_PATTERN,
            description=SEEDED_DESCRIPTION,
        )
    elif not existing.bridge_name_pattern:
        existing.bridge_name_pattern = BRIDGE_PATTERN
        existing.save(using=alias, update_fields=["bridge_name_pattern"])


def clear_bridge_pattern(apps, schema_editor):
    """Remove only the default bridge rule while preserving operator changes."""
    alias = schema_editor.connection.alias
    PortStackLagPattern = apps.get_model("netbox_librenms_plugin", "PortStackLagPattern")
    rows = PortStackLagPattern.objects.using(alias)
    existing = next((row for row in rows.all() if _normalized(row.librenms_os) == BRIDGE_OS), None)
    if existing is None or existing.bridge_name_pattern != BRIDGE_PATTERN:
        return
    if (
        existing.librenms_os == BRIDGE_OS
        and existing.lag_name_pattern == LAG_PATTERN
        and not existing.sap_name_pattern
        and existing.description == SEEDED_DESCRIPTION
    ):
        existing.delete(using=alias)
        return
    existing.bridge_name_pattern = ""
    existing.save(using=alias, update_fields=["bridge_name_pattern"])


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_librenms_plugin", "0018_device_serial_trim_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="portstacklagpattern",
            name="bridge_name_pattern",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.RunPython(populate_bridge_pattern, clear_bridge_pattern),
    ]
